# SPDX-License-Identifier: GPL-2.0-only
# Copyright (C) 2025 CPU bot Contributors
#
# CPU bot - A next-generation EESSI build-and-deploy bot.
#
# This file defines the Hound CI.
ruff:
  enabled: true
  config_file: pyproject.toml
